import Dexie, { type EntityTable } from 'dexie';

// Type definitions for our database tables

export interface OpenAPISpec {
  id?: number;
  name: string;
  content: string; // JSON stringified OpenAPI spec
  format: 'yaml' | 'json';
  collectionId?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Collection {
  id?: number;
  name: string;
  parentId?: number; // For nested collections
  color?: string;
  icon?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Endpoint {
  id?: number;
  specId: number; // References OpenAPISpec
  collectionId?: number; // Optional collection assignment
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
  path: string;
  operationId?: string;
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: any; // OpenAPI parameter schema
  requestBody?: any; // OpenAPI request body schema
  responses?: any; // OpenAPI responses schema
  security?: any; // OpenAPI security requirements
  createdAt: Date;
}

export interface Visualization {
  id?: number;
  endpointId: number; // References Endpoint
  componentCode: string; // React component code generated by AI
  prompt: string; // The prompt sent to Claude
  model: string; // AI model used (e.g., "claude-3-5-haiku")
  responseStructure: string; // JSON stringified response structure
  createdAt: Date;
  updatedAt: Date;
}

export interface RequestHistory {
  id?: number;
  endpointId: number; // References Endpoint
  environmentId?: number; // Which environment was used
  request: {
    url: string;
    method: string;
    headers: Record<string, string>;
    body?: string;
    params?: Record<string, string>;
  };
  response: {
    status: number;
    statusText: string;
    headers: Record<string, string>;
    body: string;
    duration: number; // in milliseconds
  };
  createdAt: Date;
}

export interface Environment {
  id?: number;
  name: string;
  variables: Record<string, string>; // key-value pairs like {baseUrl: "https://api.example.com"}
  isActive: boolean; // Only one can be active at a time
  createdAt: Date;
  updatedAt: Date;
}

export interface AuthConfig {
  id?: number;
  endpointId?: number; // Optional: per-endpoint auth
  collectionId?: number; // Optional: per-collection auth
  type: 'none' | 'apiKey' | 'bearer' | 'basic';
  config: {
    // For apiKey
    key?: string;
    value?: string;
    addTo?: 'header' | 'query';
    // For bearer
    token?: string;
    // For basic
    username?: string;
    password?: string;
  };
  createdAt: Date;
  updatedAt: Date;
}

// Dexie database class
class APIVisualizerDB extends Dexie {
  specs!: EntityTable<OpenAPISpec, 'id'>;
  collections!: EntityTable<Collection, 'id'>;
  endpoints!: EntityTable<Endpoint, 'id'>;
  visualizations!: EntityTable<Visualization, 'id'>;
  history!: EntityTable<RequestHistory, 'id'>;
  environments!: EntityTable<Environment, 'id'>;
  authConfigs!: EntityTable<AuthConfig, 'id'>;

  constructor() {
    super('APIVisualizerDB');
    this.version(1).stores({
      specs: '++id, name, collectionId, createdAt',
      collections: '++id, name, parentId, createdAt',
      endpoints: '++id, specId, collectionId, method, path, createdAt',
      visualizations: '++id, endpointId, createdAt',
      history: '++id, endpointId, environmentId, createdAt',
      environments: '++id, name, isActive, createdAt',
      authConfigs: '++id, endpointId, collectionId, type, createdAt',
    });
  }

  // Helper method to get active environment
  async getActiveEnvironment(): Promise<Environment | undefined> {
    return await this.environments.where('isActive').equals(1).first();
  }

  // Helper method to set active environment
  async setActiveEnvironment(id: number): Promise<void> {
    await this.transaction('rw', this.environments, async () => {
      // Deactivate all environments
      await this.environments.toCollection().modify({ isActive: false });
      // Activate the selected one
      await this.environments.update(id, { isActive: true });
    });
  }

  // Helper method to get endpoints for a collection
  async getEndpointsByCollection(collectionId: number): Promise<Endpoint[]> {
    return await this.endpoints.where('collectionId').equals(collectionId).toArray();
  }

  // Helper method to get visualization for an endpoint
  async getVisualizationForEndpoint(endpointId: number): Promise<Visualization | undefined> {
    return await this.visualizations
      .where('endpointId')
      .equals(endpointId)
      .reverse()
      .first();
  }

  // Helper method to get recent history for an endpoint
  async getRecentHistory(endpointId: number, limit: number = 50): Promise<RequestHistory[]> {
    return await this.history
      .where('endpointId')
      .equals(endpointId)
      .reverse()
      .limit(limit)
      .toArray();
  }

  // Helper method to cleanup old history (keep only last 50 per endpoint)
  async cleanupHistory(endpointId: number): Promise<void> {
    const allHistory = await this.history
      .where('endpointId')
      .equals(endpointId)
      .reverse()
      .toArray();

    if (allHistory.length > 50) {
      const toDelete = allHistory.slice(50).map(h => h.id!);
      await this.history.bulkDelete(toDelete);
    }
  }
}

// Export a singleton instance
export const db = new APIVisualizerDB();
